"""init commit

Revision ID: 7b51ce9cb5a0
Revises: 
Create Date: 2025-05-24 12:49:45.435975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b51ce9cb5a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色Id'),
    sa.Column('role_name', sa.VARCHAR(length=64), nullable=True, comment='角色名字'),
    sa.Column('permission_id', sa.BIGINT(), nullable=True, comment='权限ID'),
    sa.Column('re_mark', sa.VARCHAR(length=128), nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('id', 'role_id'),
    comment='管理员角色'
    )
    op.create_index(op.f('ix_admin_role_role_id'), 'admin_role', ['role_id'], unique=False)
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.VARCHAR(length=16), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True, comment='管理员昵称'),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True, comment='管理员头像'),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=True, comment='邮箱是否激活 0=未激活 1=激活'),
    sa.Column('role_id', sa.Integer(), nullable=True, comment='角色表'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='管理员表'
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_index(op.f('ix_admin_user_phone'), 'admin_user', ['phone'], unique=True)
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_name', sa.Text(), nullable=True, comment='名称'),
    sa.Column('ip', sa.Text(), nullable=True, comment='IP'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口'),
    sa.Column('username', sa.Text(), nullable=True, comment='用户名'),
    sa.Column('password', sa.Text(), nullable=True, comment='密码'),
    sa.Column('host_type', sa.Text(), nullable=True, comment='类型,默认工作节点'),
    sa.Column('host_status', sa.Integer(), nullable=True, comment='状态,是否在线'),
    sa.Column('is_verify', sa.Boolean(), nullable=True, comment='是否免密登录'),
    sa.Column('uuid', sa.Text(), nullable=True, comment='uuid识别号'),
    sa.Column('desc', sa.Text(), nullable=True, comment='描述'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mall_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True, comment='用户昵称'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('country_id', sa.Integer(), nullable=True, comment='国家Id'),
    sa.Column('province_id', sa.Integer(), nullable=True, comment='省id'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='市id'),
    sa.Column('district_id', sa.Integer(), nullable=True, comment='区id'),
    sa.Column('address', sa.VARCHAR(length=128), nullable=True, comment='详细地址'),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True, comment='手机号'),
    sa.Column('is_default', sa.SmallInteger(), server_default='0', nullable=True, comment='是否默认地址'),
    sa.PrimaryKeyConstraint('id'),
    comment='地址表'
    )
    op.create_table('mall_search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=64), nullable=True, comment='搜索关键词'),
    sa.Column('search_origin', sa.SmallInteger(), server_default='1', nullable=True, comment='搜索来源 1=小程序 2=APP 3=PC'),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.PrimaryKeyConstraint('id'),
    comment='搜索记录'
    )
    op.create_index(op.f('ix_mall_search_history_user_id'), 'mall_search_history', ['user_id'], unique=False)
    op.create_table('mall_site_notice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enabled', sa.SmallInteger(), server_default='1', nullable=True, comment='是否开启 0=为开启 1=开启'),
    sa.Column('content', sa.VARCHAR(length=256), nullable=True, comment='全局消息通知'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='站点消息'
    )
    op.create_table('mall_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=True, comment='用户id'),
    sa.Column('nickname', sa.VARCHAR(length=128), nullable=True, comment='用户昵称(显示用可更改)'),
    sa.Column('username', sa.VARCHAR(length=128), nullable=True, comment='用户名(不可更改)'),
    sa.Column('avatar', sa.VARCHAR(length=256), nullable=True, comment='用户头像'),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False, comment='密码'),
    sa.Column('phone', sa.VARCHAR(length=16), nullable=True, comment='手机号'),
    sa.Column('gender', sa.SmallInteger(), server_default='0', nullable=True, comment='性别 0=未知 1=男 2=女'),
    sa.Column('register_time', sa.DateTime(), nullable=True, comment='注册事件'),
    sa.Column('last_login_time', sa.DateTime(), nullable=True, comment='上次登录时间'),
    sa.Column('last_login_ip', sa.VARCHAR(length=64), nullable=True, comment='上次登录IP'),
    sa.Column('register_ip', sa.VARCHAR(length=64), nullable=True, comment='注册IP'),
    sa.Column('weixin_openid', sa.VARCHAR(length=64), nullable=True, comment='微信openId'),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True, comment='国家'),
    sa.Column('province', sa.VARCHAR(length=64), nullable=True, comment='省'),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True, comment='市'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_mall_user_phone'), 'mall_user', ['phone'], unique=True)
    op.create_index(op.f('ix_mall_user_user_id'), 'mall_user', ['user_id'], unique=True)
    op.create_table('project',
    sa.Column('project_id', sa.String(length=50), nullable=False, comment='项目Id'),
    sa.Column('project_name', sa.Text(), nullable=True, comment='项目'),
    sa.Column('project_desc', sa.Text(), nullable=True, comment='简介'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True, comment='标题'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.String(length=8), nullable=True),
    sa.Column('identity_card', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=32), nullable=True),
    sa.Column('work_start', sa.Date(), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('introduction', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('project_id', sa.String(length=50), nullable=True, comment='项目Id'),
    sa.Column('task_id', sa.String(length=50), nullable=False, comment='task_id'),
    sa.Column('task_name', sa.Text(), nullable=True, comment='名称'),
    sa.Column('task_desc', sa.Text(), nullable=True, comment='描述'),
    sa.Column('task_level', sa.Text(), nullable=True, comment='运行频率等级'),
    sa.Column('task_status', sa.Integer(), nullable=True, comment='当前状态'),
    sa.Column('local_path', sa.Text(), nullable=True, comment='本地zip目录'),
    sa.Column('remote_path', sa.Text(), nullable=True, comment='服务器目录'),
    sa.Column('deployed_hosts', sa.Text(), nullable=True, comment='已部署主机列表'),
    sa.Column('last_run_status', sa.Integer(), nullable=True, comment='最后运行状态'),
    sa.Column('last_run_time', sa.DateTime(), nullable=True, comment='最后运行时间'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=50), nullable=True),
    sa.Column('host', sa.String(length=50), nullable=True, comment='主机节点'),
    sa.Column('task_log_msg', sa.Text(), nullable=True, comment='日志信息'),
    sa.Column('task_log_level', sa.Text(), nullable=True, comment='日志等级'),
    sa.Column('update_time', sa.Text(), nullable=True, comment='记录时间'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_log')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('todos')
    op.drop_table('project')
    op.drop_index(op.f('ix_mall_user_user_id'), table_name='mall_user')
    op.drop_index(op.f('ix_mall_user_phone'), table_name='mall_user')
    op.drop_table('mall_user')
    op.drop_table('mall_site_notice')
    op.drop_index(op.f('ix_mall_search_history_user_id'), table_name='mall_search_history')
    op.drop_table('mall_search_history')
    op.drop_table('mall_address')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_admin_user_phone'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    op.drop_index(op.f('ix_admin_role_role_id'), table_name='admin_role')
    op.drop_table('admin_role')
    # ### end Alembic commands ###
